In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("BankNote_Authentication.csv")

In [3]:
df.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [4]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [5]:
X

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [6]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25,random_state=42)

In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [9]:
y_pred=classifier.predict(X_test)

In [10]:
#Accuracy using confusion matrix 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[191,   0],
       [  2, 150]], dtype=int64)

In [11]:
#Accuracy
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)
acc

0.9941690962099126

In [12]:
tp=cm[0][0]
fp=cm[0][1]
tn=cm[1][1]
fn=cm[1][0]
precision=tp/(tp+fp)
precision

1.0

In [13]:
recall=tp/(tp+fn)
recall

0.9896373056994818

In [14]:
#F1 = 2 * (precision * recall) / (precision + recall)
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, zero_division=1)

0.9933774834437086

In [15]:
#Pickle file
import pickle
pickle_out=open("classifier.pkl","wb")
pickle.dump(classifier,pickle_out)
pickle_out.close()

In [16]:
#prediction
classifier.predict([[2,3,4,1]])

array([0], dtype=int64)